from enum import Enum

class CMD(Enum):
    ECHO=0
    TOF_READINGS=1
    GO_FORWARD=2
    PID_STATUS_INI=3
    PID_FD=4
    GYR_READINGS = 5
    SEND_PID_FD_DEBUG_READINGS=6
    PID_ORIENT = 7
    SEND_PID_ORIENT_DEBUG_READINGS = 8
    KALMAN_FILTER_TEST = 9
    DRIFT_STUNT = 10
    SEND_DRIFT_DEBUG_READINGS = 11
    PID_ANGLE_INCREMENT = 12
    SEND_PID_ANGLE_INCREMENT_DEBUG_READINGS = 13
    SET_PID_VALUES = 14
    SET_ORIENT_PID_VALUES = 15
    PID_ROTATE = 16
    PID_TRANS = 17
    SET_FORWARD_SPEED = 18
    SET_FD_CALI = 19
    
    # ECHO,
    # TOF_READINGS,
    # GO_FORWARD,
    # PID_STATUS_INI,
    # PID_FD,
    # GYR_READINGS,
    # SEND_PID_FD_DEBUG_READINGS,
    # PID_ORIENT,
    # SEND_PID_ORIENT_DEBUG_READINGS,
    # KALMAN_FILTER_TEST,
    # DRIFT_STUNT,
    # SEND_DRIFT_DEBUG_READINGS,
    # PID_ANGLE_INCREMENT,
    # SEND_PID_ANGLE_INCREMENT_DEBUG_READINGS,
    # SET_PID_VALUES,
    # SET_ORIENT_PID_VALUES,
    # PID_ROTATE,
    # PID_TRANS,